export const events = [
  {
    title: "Next.js Conf 2026",
    image: "/images/event1.png",
    slug: "nextjs-conf-2026",
    location: "San Francisco, CA",
    date: "Oct 22, 2026",
    time: "09:00 AM",
  },
  {
    title: "React Summit Europe",
    image: "/images/event2.png",
    slug: "react-summit-2026",
    location: "Amsterdam, NL",
    date: "June 12, 2026",
    time: "10:00 AM",
  },
  {
    title: "Web Summit 2026",
    image: "/images/event3.png",
    slug: "web-summit-2026",
    location: "Lisbon, Portugal",
    date: "Nov 10, 2026",
    time: "09:30 AM",
  },
  {
    title: "AWS re:Invent 2026",
    image: "/images/event4.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "Dec 01, 2026",
    time: "08:00 AM",
  },
  {
    title: "Google I/O 2026",
    image: "/images/event5.png",
    slug: "google-io-2026",
    location: "Mountain View, CA",
    date: "May 12, 2026",
    time: "10:00 AM",
  },
  {
    title: "Microsoft Build 2026",
    image: "/images/event6.png",
    slug: "microsoft-build-2026",
    location: "Seattle, WA",
    date: "May 19, 2026",
    time: "09:00 AM",
  },
  {
    title: "Apple WWDC 2026",
    image: "/images/event-full.png",
    slug: "apple-wwdc-2026",
    location: "Cupertino, CA",
    date: "June 08, 2026",
    time: "10:00 AM",
  },
  {
    title: "KubeCon + CloudNativeCon 2026",
    image: "/images/event2.png",
    slug: "kubecon-2026",
    location: "Los Angeles, CA",
    date: "Nov 17, 2026",
    time: "09:00 AM",
  },
];
